serialcontroller.host=127.0.0.1
serialcontroller.port=8000
serialcontroller.log.level=INFO
serialcontroller.max.setvoltage=12
serialcontroller.max.setcurrent=2
serialcontroller.admin.username=serialcontroller
serialcontroller.admin.password=secret
